# 测试配置文件
# 
# 
server:
  port: 8801
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://20.26.39.25:3306/datalake?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true
    username: datalake
    password: ENC(NE1OI11ay/EZL/CUKKzDwzaCMyZMiexSuonH6l/8B2DrNCz9g+/tqqHeIaiifbQC)
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 20.26.26.27
    port: 6390
    timeout: 5000
  # Elasticsearch 配置
  # todo 需替换配置
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456