spring:
  application:
    name: springboot-init
  # 默认 dev 环境
  profiles:
    active: test
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paopaoba
    username: root
    password: briup
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    redisson:
      file: classpath:redisson.yaml
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  address: 0.0.0.0
  port: 8801
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 线程池配置参数
thread-pool:
  corePoolSize: 5 # 设置核心线程数
  maxPoolSize: 20 # 设置最大线程数
  keepAliveSeconds: 300 # 设置空闲线程存活时间（秒）
  queueCapacity: 50 # 设置队列容量
  threadNamePrefix: "-customAsyncThreadPool-" # 设置线程名称前缀
  awaitTerminationSeconds: 60 #  设置线程池等待终止时间(秒)

jasypt:
  encryptor:
    password: U2FsdGVkX19BKaGaSUdKRto9s5+17IaGIEgT8Cf9jKY=
dubbo:
  application:
    name: dubbo-springboot-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
